/// Product dimension. One row per product_id. The Portuguese category name is
/// joined to product_category_name_translation to produce an English, title-cased
/// Category. Relates to Fact_OrderItems (order-line grain) only.
table Dim_Product
	lineageTag: 566bc57c-16cb-43f6-8b5f-03683bf5b271

	column product_id
		dataType: string
		isHidden
		isKey
		lineageTag: ff7609f8-62b4-4c12-a6ef-0c67b381f9cb
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 72beb2cb-46ed-4017-aa1c-41b7b9e90c93
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = None

	partition Dim_Product = m
		mode: import
		source =
				let
				    Products = fnLoadCsv("olist_products_dataset.csv"),
				    Translation = fnLoadCsv("product_category_name_translation.csv"),
				    Joined = Table.NestedJoin(Products, {"product_category_name"}, Translation, {"product_category_name"}, "T", JoinKind.LeftOuter),
				    Expanded = Table.ExpandTableColumn(Joined, "T", {"product_category_name_english"}, {"category_en"}),
				    AddRaw = Table.AddColumn(Expanded, "CategoryRaw", each if [category_en] <> null and [category_en] <> "" then [category_en] else (if [product_category_name] <> null and [product_category_name] <> "" then [product_category_name] else "unknown"), type text),
				    AddPretty = Table.AddColumn(AddRaw, "Category", each Text.Proper(Text.Replace([CategoryRaw], "_", " ")), type text),
				    Selected = Table.SelectColumns(AddPretty, {"product_id", "Category"}),
				    Typed = Table.TransformColumnTypes(Selected, {{"product_id", type text}, {"Category", type text}})
				in
				    Typed

	annotation PBI_ResultType = Table

